kind: Service
apiVersion: v1
metadata:
  name: web1-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: web1
  ports:
    - port: 80 # Default port for image
      nodePort: 31000
---
kind: Service
apiVersion: v1
metadata:
  name: web2-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: web2
  ports:
    - port: 3000 # Default port for image
      nodePort: 31001
---
kind: Service
apiVersion: v1
metadata:
  name: web-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80 # Default port for image
      nodePort: 31003
